### ISSUE TITLE
Dynamically change helper configuration from inside the component

### ISSUE THREAD

**Issue by harshmaur** [algolia/algoliasearch-helper-provider#17]
I wanted to know how can I change the helper configuration inside the component. There are certain cases when I want to set distinct to true and sometimes to false. There can be cases when I want to add any field to facet configuration.

**Comment by alexkirsz** [comment]
Your connected components have access to the helper instance in their props, so you can change helper configuration during a component's lifecycle, as well as during discrete events.

``` js
class DistinctToggle extends Component {
  constructor() {
    super();

    this.onClick = this.onClick.bind(this);
  }

  // Component lifecycle
  componentDidMount() {
    this.props.helper.setQueryParameter('distinct', true).search();
  }

  // Discrete event
  onClick() {
    this.props.helper.setQueryParameter('distinct', !this.props.distinct).search();
  }

  render() {
    return (
      <button onClick={this.onClick}>
        Toggle distinct {this.props.distinct ? 'off' : 'on'}
      </button>
    );
  }
}

DistinctToggle.propTypes = {
  helper: PropTypes.object.isRequired,
  distinct: PropTypes.bool.isRequired,
};

export default connect(state => ({
  distinct: state.searchParameters.distinct,
}))(DistinctToggle);
```

Is this what you are looking for? 

Note that calling any `set` function on the helper will trigger its `change` event and produce a new state, that will be passed down to connected components. Thus, doing multiple `set` calls in a row can lead to superfluous and unwanted re-renders.

To avoid this, you should make your helper state updates atomic, by manipulating the helper's SearchParameters object directly and doing only one `setState` call.

For instance, instead of doing this:

``` js
// Initial state: prevState
// Intermediary state: { ...prevState, distinct: true }
// Final state: { ...prevState, distinct: true, hitsPerPage: 30 }
helper.setQueryParameter('distinct', true).setQueryParameter('hitsPerPage', 30).search();
```

You should do this:

``` js
// Initial state: prevState
// Final state: { ...prevState, distinct: true, hitsPerPage: 30 }
helper.setState(
  helper
    .getState()
    .setQueryParameter('distinct', true)
    .setQueryParameter('hitsPerPage', 30)
).search();
```

See the documentation on [helper.setState](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#setState) and [SearchParameters](https://community.algolia.com/algoliasearch-helper-js/reference.html#searchparameters).

**Comment by harshmaur** [comment]
Yes, this works for me, however when I am changing components. For example, First I am on listing page where I need distinct to be "true" and when I click on a product(Single Page Component), distinct needs to be "false". 

I have set distinct to false in my single page component however when I go back to my listing page, distinct is still false. It needs to be true again. 

So do I need to manipulate the QueryParameter on all components if I change any configuration?

**Comment by alexkirsz** [comment]
You can use the [`componentWillUnmount`](https://facebook.github.io/react/docs/component-specs.html#unmounting-componentwillunmount) lifecycle method in order to reset distinct to its previous value upon unmounting your product component.

``` js
class Product extends Component {
  constructor(props) {
    super();

    this.previousDistinct = props.helper.getQueryParameter('distinct');
  }

  componentDidMount() {
    this.props.helper.setQueryParameter('distinct', true).search();
  }

  componentWillUnmount() {
    this.props.helper.setQueryParameter('distinct', this.previousDistinct).search();
  }

  render() {
    /* ... */
  }
}
```

You could also control this outside of the Product component, or use a different helper on the Product page.

**Comment by harshmaur** [comment]
Great. It works! 

One thing I found while navigating between components is that we need to clear all refinements on every component where we want to use the helper as it tends to preserve the refinements in the state. 

I am not sure if not clearing the refinements is ideal or not. I feel that helper method should be "refreshed" to original state when components change.

**Comment by alexkirsz** [comment]
A helper holds the state for one search. If you have searches with wildly different parameters, you might be better off using different helpers. In this case, you would also use multiple `<Provider>` components, wrapping the UI components that depend on the state of the corresponding helper.

Taking the previous example a bit further, you could also do:

``` js
class Product extends Component {
  constructor(props) {
    super();

    this.previousHelperState = props.helper.getState();
  }

  componentDidMount() {
    // Add your refinements here
  }

  componentWillUnmount() {
    // Completely reset the state to what it was before <Product> mounted
    this.props.helper.setState(this.previousHelperState).search();
  }

  render() {
    /* ... */
  }
}
```

But be aware that this will completely reset the helper state to what it was before the component was mounted, including the query and the page.

**Comment by harshmaur** [comment]
Exactly what I was looking for! 
Thanks!
